[package]
name = "serial-port-multiplexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "mux-serial-server"
path = "src/mux-serial-server.rs"
